import { useEffect, useMemo, useState } from 'react';
import { useMutation, useQuery } from '@tanstack/react-query';
import { ArrowLeft, Banknote, CalendarDays, CheckCircle2, CircleUserRound, ClipboardCheck, Clock3, FileCheck2, MessageCircle, NotebookPen, Phone, Save, ShieldCheck, Sparkles, UserPlus2, UsersRound } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { calculateDealValue, canTransitionStatus, pipelineStatuses, type ProspectStatus } from '@csumroh/shared-types';
import { api } from '../../lib/api';
import { useBrandScope } from '../../lib/scope';
import { useAuth } from '../../app/auth';
import { queryClient } from '../../app/query';
import { Badge, statusLabels } from '../../components/ui/badge';
import { Button } from '../../components/ui/button';
import { Select } from '../../components/ui/select';
import { PageError, PageLoading } from '../../components/ui/page-feedback';

const n = (value: unknown) => Number(String(value ?? 0).replace(/\D/g, '')) || 0;
const rupiah = (value: unknown) => new Intl.NumberFormat('id-ID', { style:'currency',currency:'IDR',maximumFractionDigits:0 }).format(Number(value ?? 0));

export function ProspectDetailPage() {
  const { id } = useParams(); const { user } = useAuth(); const { brandId, query } = useBrandScope(); const [tab,setTab] = useState<'profile'|'activity'|'tgjp'>('profile'); const [form,setForm] = useState<any>({});
  const prospect = useQuery({ queryKey:['prospect',id,brandId], queryFn:()=>api.get<any>(`/prospects/${id}${query}`), enabled:!!id&&!!brandId });
  const packages = useQuery({ queryKey:['packages',brandId], queryFn:()=>api.get<any[]>(`/catalog/packages${query}`), enabled:!!brandId });
  useEffect(()=>{if(prospect.data)setForm({targetMonth:prospect.data.targetMonth??'',budgetRange:prospect.data.budgetRange??'',decisionMaker:prospect.data.decisionMaker??'',specialNeeds:prospect.data.specialNeeds??'',passportStatus:prospect.data.passportStatus??'',vaccineStatus:prospect.data.vaccineStatus??'',paxQuad:prospect.data.paxQuad??0,paxTriple:prospect.data.paxTriple??0,paxDouble:prospect.data.paxDouble??0,paxInfant:prospect.data.paxInfant??0,dpAmount:Number(prospect.data.dpAmount??0),paymentStatus:prospect.data.paymentStatus,notes:prospect.data.notes??'',nextFollowupDate:prospect.data.nextFollowupDate?.slice(0,10)??'',packageId:prospect.data.packageId?String(prospect.data.packageId):''});},[prospect.data]);
  const selectedPackage = packages.data?.find((p)=>String(p.id)===form.packageId);
  const dealValue = useMemo(()=>calculateDealValue({quad:n(selectedPackage?.priceQuad||selectedPackage?.price),triple:n(selectedPackage?.priceTriple||selectedPackage?.price),double:n(selectedPackage?.priceDouble||selectedPackage?.price),infant:n(selectedPackage?.priceInfant)}, {quad:Number(form.paxQuad),triple:Number(form.paxTriple),double:Number(form.paxDouble),infant:Number(form.paxInfant)}),[form.paxQuad,form.paxTriple,form.paxDouble,form.paxInfant,selectedPackage]);
  const save = useMutation({mutationFn:()=>api.patch(`/prospects/${id}/profile`,{...form,packageId:form.packageId?Number(form.packageId):null,dealValue,nextFollowupDate:form.nextFollowupDate?`${form.nextFollowupDate}T00:00:00.000Z`:null,...(user?.role==='superadmin'?{brandId}:{})}),onSuccess:()=>{void queryClient.invalidateQueries({queryKey:['prospect',id]});void queryClient.invalidateQueries({queryKey:['prospects']});}});
  const status = useMutation({mutationFn:(value:string)=>api.patch(`/prospects/${id}/status`,{status:value,...(user?.role==='superadmin'?{brandId}:{})}),onSuccess:()=>{void queryClient.invalidateQueries({queryKey:['prospect',id]});}});
  const claim = useMutation({mutationFn:()=>api.post(`/prospects/${id}/claim`),onSuccess:()=>void queryClient.invalidateQueries({queryKey:['prospect',id]})});
  const p=prospect.data; if(prospect.isLoading)return <PageLoading label="Memuat profil prospek"/>; if(prospect.isError)return <PageError title="Profil tidak dapat dimuat" description={prospect.error.message} onRetry={()=>void prospect.refetch()}/>; if(!p)return <PageError title="Prospek tidak ditemukan" description="Data prospek ini tidak tersedia atau sudah dipindahkan."/>;
  return <div className="app-page">
    <Link to="/pipeline" className="inline-flex items-center gap-2 text-xs font-bold text-zinc-500 hover:text-black"><ArrowLeft size={15}/>Kembali ke pipeline</Link>
    <section className="surface overflow-hidden"><div className="bg-zinc-950 px-5 py-6 text-white sm:px-7"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-center"><div className="flex items-center gap-4"><span className="grid h-14 w-14 place-items-center rounded-2xl bg-white text-lg font-extrabold text-zinc-950">{p.name.slice(0,2).toUpperCase()}</span><div><div className="mb-2 flex flex-wrap items-center gap-2"><h2 className="font-display text-2xl font-extrabold tracking-tight">{p.name}</h2><Badge value={p.status}/></div><p className="text-xs text-zinc-400">{p.phone} · {p.city||'Kota belum diisi'} · {p.leadSource}</p></div></div><div className="flex gap-2">{user?.role==='cs'&&!p.user&&<Button variant="secondary" onClick={()=>claim.mutate()}><UserPlus2 size={15}/>Klaim PIC</Button>}<Link to={`/inbox?prospectId=${p.id}${p.phone?`&phone=${encodeURIComponent(p.phone)}`:''}${p.remoteJid?`&jid=${encodeURIComponent(p.remoteJid)}`:''}`}><Button className="bg-white text-black hover:bg-zinc-200"><MessageCircle size={16}/>Buka di kotak masuk</Button></Link></div></div></div>
      <div className="grid divide-y sm:grid-cols-4 sm:divide-x sm:divide-y-0">{[[Banknote,rupiah(dealValue),'Estimasi deal'],[UsersRound,`${Number(form.paxQuad)+Number(form.paxTriple)+Number(form.paxDouble)+Number(form.paxInfant)} pax`,'Jumlah jamaah'],[CircleUserRound,p.user?.name??'Belum ada','CS PIC'],[CalendarDays,p.nextFollowupDate?new Date(p.nextFollowupDate).toLocaleDateString('id-ID'):'Belum diatur','Follow-up']].map(([Icon,value,label])=>{const I=Icon as typeof Banknote;return <div key={String(label)} className="flex items-center gap-3 px-5 py-4"><span className="grid h-9 w-9 place-items-center rounded-xl bg-zinc-100"><I size={17}/></span><div><b className="block text-sm">{String(value)}</b><span className="text-[10px] uppercase tracking-wide text-zinc-400">{String(label)}</span></div></div>})}</div>
    </section>
    <div className="flex gap-1 overflow-x-auto border-b">{[['profile','Profil 360°'],['activity','Aktivitas'],['tgjp','Wizard TGJP']].map(([value,label])=><button key={value} onClick={()=>setTab(value as typeof tab)} className={`whitespace-nowrap border-b-2 px-4 py-3 text-xs font-bold ${tab===value?'border-black text-black':'border-transparent text-zinc-400'}`}>{label}</button>)}</div>
    {tab==='profile'&&<div className="grid gap-5 xl:grid-cols-[1fr_340px]"><div className="space-y-5"><FormSection icon={NotebookPen} title="Kualifikasi NPGD" subtitle="Need, Priority, Group, Decision maker"><div className="grid gap-4 sm:grid-cols-2"><Field label="Target keberangkatan"><input className="field" value={form.targetMonth} onChange={(e)=>setForm({...form,targetMonth:e.target.value})} placeholder="Contoh: Ramadan 1448H"/></Field><Field label="Kisaran budget"><input className="field" value={form.budgetRange} onChange={(e)=>setForm({...form,budgetRange:e.target.value})} placeholder="Contoh: 30–35 juta"/></Field><Field label="Pengambil keputusan"><input className="field" value={form.decisionMaker} onChange={(e)=>setForm({...form,decisionMaker:e.target.value})} placeholder="Diri sendiri / pasangan"/></Field><Field label="Kebutuhan khusus"><input className="field" value={form.specialNeeds} onChange={(e)=>setForm({...form,specialNeeds:e.target.value})} placeholder="Kursi roda, lansia…"/></Field></div></FormSection>
        <FormSection icon={UsersRound} title="Kamar & jumlah jamaah" subtitle="Nilai deal dihitung otomatis dari harga paket"><Field label="Paket pilihan"><Select value={form.packageId} onValueChange={(packageId)=>setForm({...form,packageId})} options={(packages.data??[]).map((item)=>({value:String(item.id),label:String(item.name)}))} placeholder="Pilih paket" className="w-full"/></Field><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4">{([['paxQuad','Quad'],['paxTriple','Triple'],['paxDouble','Double'],['paxInfant','Infant']] as const).map(([key,label])=><Field key={key} label={label}><input type="number" min="0" className="field" value={form[key]} onChange={(e)=>setForm({...form,[key]:Number(e.target.value)})}/></Field>)}</div><div className="mt-4 rounded-xl bg-zinc-950 p-4 text-white"><p className="text-[10px] uppercase tracking-[.12em] text-zinc-500">Estimasi nilai transaksi</p><p className="mt-1 font-display text-xl font-extrabold">{rupiah(dealValue)}</p></div></FormSection>
        <FormSection icon={FileCheck2} title="Dokumen & finansial" subtitle="Pantau kesiapan jamaah sebelum keberangkatan"><div className="grid gap-4 sm:grid-cols-2"><Field label="Status paspor"><Select value={form.passportStatus} onValueChange={(passportStatus)=>setForm({...form,passportStatus})} options={([['sudah_ada','Sudah ada'],['proses_buat','Proses buat'],['perpanjang','Perpanjang'],['belum_ada','Belum ada']] as const).map(([value,label])=>({value,label}))} className="w-full" placeholder="Pilih status"/></Field><Field label="Status vaksin"><Select value={form.vaccineStatus} onValueChange={(vaccineStatus)=>setForm({...form,vaccineStatus})} options={([['lengkap','Lengkap'],['proses','Sedang proses'],['belum','Belum vaksin']] as const).map(([value,label])=>({value,label}))} className="w-full" placeholder="Pilih status"/></Field><Field label="DP masuk"><input type="number" className="field" value={form.dpAmount} onChange={(e)=>setForm({...form,dpAmount:Number(e.target.value)})}/></Field><Field label="Status pembayaran"><Select value={form.paymentStatus} onValueChange={(paymentStatus)=>setForm({...form,paymentStatus})} options={([['unpaid','Belum bayar'],['partial_dp','DP sebagian'],['paid_full','Lunas']] as const).map(([value,label])=>({value,label}))} className="w-full"/></Field></div></FormSection></div>
      <aside className="space-y-5"><div className="surface p-5"><h3 className="font-display font-bold">Kontrol pipeline</h3><p className="mt-1 text-xs text-zinc-400">Perbarui tahap dan jadwal tindak lanjut.</p><div className="mt-5 space-y-4"><Field label="Status"><Select value={p.status} onValueChange={(v)=>status.mutate(v)} options={pipelineStatuses.filter((value)=>canTransitionStatus(p.status as ProspectStatus,value)).map((value)=>({value,label:statusLabels[value] ?? value}))} className="w-full"/></Field><Field label="Follow-up berikutnya"><input type="date" className="field" value={form.nextFollowupDate} onChange={(e)=>setForm({...form,nextFollowupDate:e.target.value})}/></Field><Field label="Catatan internal"><textarea rows={6} className="w-full resize-none rounded-xl border p-3 text-sm" value={form.notes} onChange={(e)=>setForm({...form,notes:e.target.value})}/></Field><Button className="w-full" onClick={()=>save.mutate()} disabled={save.isPending}><Save size={15}/>{save.isPending?'Menyimpan…':'Simpan perubahan'}</Button>{save.isSuccess&&<p className="flex items-center gap-1.5 text-xs text-zinc-500"><CheckCircle2 size={14}/>Perubahan tersimpan.</p>}{(save.error||status.error)&&<p className="text-xs text-zinc-500">{(save.error||status.error)?.message}</p>}</div></div><div className="rounded-2xl border bg-zinc-50 p-5"><ShieldCheck size={20}/><h3 className="mt-4 font-display font-bold">Data brand terlindungi</h3><p className="mt-2 text-xs leading-5 text-zinc-500">Rekening dan legalitas selalu diambil dari brand akun yang aktif.</p></div></aside></div>}
    {tab==='activity'&&<div className="surface p-5 sm:p-7"><div className="max-w-3xl space-y-0">{(p.logs??[]).map((log:any,index:number)=><div key={log.id} className="relative flex gap-4 pb-7"><div className="relative z-10 grid h-9 w-9 shrink-0 place-items-center rounded-full border bg-white"><Clock3 size={15}/></div>{index<(p.logs??[]).length-1&&<div className="absolute left-[17px] top-9 h-full border-l"/>}<div className="pt-1"><div className="flex flex-wrap items-center gap-2"><b className="text-sm">{log.title}</b><span className="text-[10px] text-zinc-400">{new Date(log.createdAt).toLocaleString('id-ID')}</span></div><p className="mt-1 text-xs text-zinc-500">{log.description||`Oleh ${log.user?.name??'sistem'}`}</p></div></div>)}{!(p.logs??[]).length&&<p className="py-12 text-center text-sm text-zinc-400">Belum ada aktivitas untuk prospek ini.</p>}</div></div>}
    {tab==='tgjp'&&<TgjpWizard name={p.name}/>} 
  </div>;
}

function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="label">{label}</span>{children}</label>}
function FormSection({icon:Icon,title,subtitle,children}:{icon:typeof NotebookPen;title:string;subtitle:string;children:React.ReactNode}){return <section className="surface p-5 sm:p-6"><div className="mb-5 flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-zinc-100"><Icon size={18}/></span><div><h3 className="font-display font-bold">{title}</h3><p className="text-xs text-zinc-400">{subtitle}</p></div></div>{children}</section>}
function TgjpWizard({name}:{name:string}){const steps=[{id:'T',title:'Terima',text:`Validasi perasaan ${name} tanpa menyela atau membantah.`},{id:'G',title:'Gali',text:'Temukan akar keberatan dengan satu pertanyaan terarah.'},{id:'J',title:'Jawab',text:'Berikan solusi rasional sesuai kebutuhan dan fakta paket.'},{id:'P',title:'Pastikan',text:'Pastikan keberatan selesai dan arahkan ke komitmen mikro.'}];const [active,setActive]=useState(0);return <div className="surface p-5 sm:p-7"><div className="mb-7"><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.14em] text-zinc-400"><Sparkles size={14}/>Framework keberatan</p><h3 className="mt-2 font-display text-2xl font-extrabold">TGJP guided response</h3></div><div className="grid gap-3 md:grid-cols-4">{steps.map((step,index)=><button key={step.id} onClick={()=>setActive(index)} className={`rounded-2xl border p-4 text-left transition ${active===index?'border-zinc-950 bg-zinc-950 text-white':'bg-white hover:bg-zinc-50'}`}><span className={`grid h-8 w-8 place-items-center rounded-lg text-xs font-extrabold ${active===index?'bg-white text-black':'bg-zinc-100'}`}>{step.id}</span><b className="mt-4 block font-display">{step.title}</b><p className={`mt-2 text-xs leading-5 ${active===index?'text-zinc-400':'text-zinc-500'}`}>{step.text}</p></button>)}</div><div className="mt-6 rounded-2xl bg-zinc-100 p-5"><p className="text-[10px] font-bold uppercase tracking-[.12em] text-zinc-400">Langkah {active+1} dari 4</p><h4 className="mt-2 font-display text-lg font-bold">{steps[active]?.title}</h4><textarea className="mt-3 min-h-28 w-full resize-none rounded-xl border bg-white p-3 text-sm" placeholder={`Tulis respons tahap ${steps[active]?.title.toLowerCase()} di sini…`}/><div className="mt-3 flex justify-end"><Button onClick={()=>setActive(Math.min(3,active+1))}>{active===3?'Selesai':'Lanjutkan'}</Button></div></div></div>}
