import { describe, expect, it, vi } from 'vitest';
import { buildCapiEventId, buildCapiPayload, normalizeCity, normalizePhone, sha256, splitPersonName, validateEventValue, validateMetaConfig } from './capi.payload.js';
import { queueCapiForStatus } from './capi.service.js';

describe('Meta CAPI payload builder',()=>{
  it('normalizes Indonesian phone numbers',()=>{expect(normalizePhone('0812-3456-7890')).toBe('6281234567890');expect(normalizePhone('+62 812 3456 7890')).toBe('6281234567890');});
  it('nomor luar negeri tidak diberi awalan 62',()=>{expect(normalizePhone('966512345678')).toBe('966512345678');expect(normalizePhone('+60 12-345 6789')).toBe('60123456789');expect(buildCapiPayload({eventName:'LeadSubmitted',eventId:'e',phone:'966512345678',ctwaClid:'c',pageId:'p'}).data[0]!.user_data.country).toBeUndefined();});
  it('hashes phone but keeps the CTWA click id raw',()=>{const payload=buildCapiPayload({eventName:'Purchase',eventId:'event-1',phone:'081234567890',ctwaClid:'AR-click-id',pageId:'123456',whatsappBusinessAccountId:'987654',value:50_000_000});const serialized=JSON.stringify(payload);expect(serialized).not.toContain('081234567890');expect(serialized).toContain(sha256('6281234567890'));expect(payload.data[0]!.user_data.ctwa_clid).toBe('AR-click-id');expect(payload.data[0]!.user_data.page_id).toBe('123456');expect(payload.data[0]!.messaging_channel).toBe('whatsapp');expect(payload.data[0]!.custom_data).toEqual({currency:'IDR',value:50_000_000});});
  it('adds hashed name, city and country for match quality',()=>{const payload=buildCapiPayload({eventName:'Purchase',eventId:'e',phone:'081234567890',ctwaClid:'AR',pageId:'1',name:'Bpk. Abdullah Faqih Rahman',city:'Kota Depok'});const user=payload.data[0]!.user_data;expect(user.fn).toEqual([sha256('abdullah')]);expect(user.ln).toEqual([sha256('rahman')]);expect(user.ct).toEqual([sha256('depok')]);expect(user.country).toEqual([sha256('id')]);expect(JSON.stringify(payload)).not.toMatch(/abdullah|depok/i);});
  it('skips generic contact names and empty city',()=>{const user=buildCapiPayload({eventName:'LeadSubmitted',eventId:'e',phone:'081234567890',ctwaClid:'AR',pageId:'1',name:'+62 812-3456-7890',city:''}).data[0]!.user_data;expect(user.fn).toBeUndefined();expect(user.ln).toBeUndefined();expect(user.ct).toBeUndefined();expect(splitPersonName('Salma')).toEqual({firstName:'salma',lastName:''});expect(normalizeCity('Kab. Bogor')).toBe('bogor');});
  it('builds deterministic event ids',()=>{expect(buildCapiEventId(42,'Purchase',2)).toBe('csumroh_prospect_42_won_2');expect(buildCapiEventId(42,'Purchase',2)).toBe(buildCapiEventId(42,'Purchase',2));expect(buildCapiEventId(42,'AddToCart')).toBe('csumroh_prospect_42_offered');});
  it('requires page id (WABA optional) plus real transaction values',()=>{expect(validateMetaConfig({pixelId:'1',accessToken:'token',pageId:'2'}).valid).toBe(true);expect(validateMetaConfig({pixelId:'1',accessToken:'token',pageId:null}).valid).toBe(false);expect(validateEventValue('Purchase',0,5_000_000).valid).toBe(false);expect(validateEventValue('InitiateCheckout',50_000_000,0).valid).toBe(false);expect(validateEventValue('Purchase',50_000_000,0)).toEqual({valid:true,value:50_000_000});});
  it('queues dispatch without blocking the status update response',async()=>{const dispatch=vi.fn().mockRejectedValue(new Error('Meta unavailable'));const consoleSpy=vi.spyOn(console,'error').mockImplementation(()=>undefined);expect(queueCapiForStatus(7,'closed_won',dispatch)).toBeUndefined();expect(dispatch).toHaveBeenCalledWith(7,'closed_won');await Promise.resolve();await Promise.resolve();expect(consoleSpy).toHaveBeenCalled();consoleSpy.mockRestore();});
});
