import { useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Check, Clipboard, MessageCircle, Search, ShieldCheck, Sparkles, WandSparkles } from 'lucide-react';
import { api } from '../../lib/api';
import { useBrandScope } from '../../lib/scope';
import { Button } from '../../components/ui/button';
import { Select } from '../../components/ui/select';
import { PageError, PageLoading } from '../../components/ui/page-feedback';

const categories = [{id:'greeting',label:'Sapaan'},{id:'identification',label:'Identifikasi'},{id:'offer',label:'Penawaran'},{id:'objection',label:'Keberatan'},{id:'followups',label:'Follow-up'},{id:'closing',label:'Closing'}];
export function CopilotPage(){
  const {brandId,query}=useBrandScope();const [name,setName]=useState('');const [packageId,setPackageId]=useState('');const [active,setActive]=useState('greeting');const [search,setSearch]=useState('');const [copied,setCopied]=useState<string|null>(null);
  const packages=useQuery({queryKey:['packages',brandId],queryFn:()=>api.get<any[]>(`/catalog/packages${query}`),enabled:!!brandId});
  const separator=query?'&':'?';const scripts=useQuery({queryKey:['scripts',brandId,name,packageId],queryFn:()=>api.get<any>(`/scripts${query}${separator}nama=${encodeURIComponent(name)}${packageId?`&packageId=${packageId}`:''}`),enabled:!!brandId});
  const items=(scripts.data?.categories?.[active]?.scripts??[]) as any[];
  const filtered=useMemo(()=>items.filter((item)=>`${item.title} ${item.use_when} ${item.script}`.toLowerCase().includes(search.toLowerCase())),[items,search]);
  async function copy(item:any){await navigator.clipboard.writeText(item.script);setCopied(item.id);setTimeout(()=>setCopied(null),1800);}
  if (!brandId) return <PageError title="Belum ada brand aktif" description="Buat brand melalui menu Administrasi, lalu tambahkan paket dan skrip Copilot yang benar-benar digunakan tim." />;
  if (scripts.isLoading) return <PageLoading label="Menyiapkan Copilot" />;
  if (scripts.isError) return <PageError description={scripts.error.message} onRetry={() => void scripts.refetch()} />;
  return <div className="app-page"><section className="page-header"><div><p className="page-kicker"><WandSparkles size={14}/>Smart script copier</p><h2 className="page-title">Copilot percakapan</h2><p className="page-subtitle">Pilih konteks, personalisasikan variabel, lalu salin respons yang paling manusiawi.</p></div><div className="flex items-center gap-2 self-start rounded-full border bg-white px-3 py-2 text-xs text-zinc-500 lg:self-auto"><ShieldCheck size={15}/>Rekening terkunci sesuai brand</div></section>
    <section className="surface grid gap-4 p-4 md:grid-cols-[1fr_1fr_1.3fr]"><label><span className="label">Nama jamaah</span><input className="field" value={name} onChange={(e)=>setName(e.target.value)} placeholder="Contoh: Ibu Aisyah"/></label><label><span className="label">Paket pilihan</span><Select value={packageId} onValueChange={setPackageId} options={(packages.data??[]).map((item)=>({value:String(item.id),label:item.name}))} placeholder="Pilih paket" className="w-full"/></label><label><span className="label">Cari kebutuhan skrip</span><span className="relative block"><Search size={15} className="absolute left-3 top-3.5 text-zinc-400"/><input className="field pl-9" value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Harga, legalitas, keluarga…"/></span></label></section>
    <div className="thin-scrollbar flex gap-2 overflow-x-auto pb-1">{categories.map((item)=><button key={item.id} onClick={()=>setActive(item.id)} className={`whitespace-nowrap rounded-xl px-4 py-2.5 text-xs font-bold transition ${active===item.id?'bg-zinc-950 text-white':'border bg-white text-zinc-500 hover:bg-zinc-100'}`}>{item.label}<span className={`ml-2 rounded-full px-1.5 py-0.5 text-[9px] ${active===item.id?'bg-zinc-800':'bg-zinc-100'}`}>{(scripts.data?.categories?.[item.id]?.scripts??[]).length}</span></button>)}</div>
    <section className="grid gap-4 xl:grid-cols-2">{filtered.map((item,index)=><article key={item.id} className="surface flex flex-col p-5 transition hover:shadow-soft"><div className="flex items-start justify-between gap-3"><div><span className="text-[10px] font-bold uppercase tracking-[.12em] text-zinc-400">{item.category?.replaceAll('_',' ')||categories.find((c)=>c.id===active)?.label}</span><h3 className="mt-1 font-display font-bold leading-snug">{item.title}</h3></div><span className="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-zinc-100 text-[10px] font-extrabold">{String(index+1).padStart(2,'0')}</span></div><p className="mt-3 text-xs leading-5 text-zinc-400">{item.use_when}</p><div className="my-4 flex-1 rounded-2xl bg-zinc-50 p-4 text-sm leading-6 text-zinc-700"><p className="whitespace-pre-wrap">{item.script}</p></div><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex flex-wrap gap-1">{item.tags?.slice(0,3).map((tag:string)=><span key={tag} className="rounded-full bg-zinc-100 px-2 py-1 text-[9px] font-semibold text-zinc-500">#{tag}</span>)}</div><div className="flex shrink-0 gap-2"><Button variant="secondary" size="sm" onClick={()=>void copy(item)}>{copied===item.id?<Check size={14}/>:<Clipboard size={14}/>} {copied===item.id?'Tersalin':'Salin'}</Button><Button size="sm" onClick={()=>window.open(`https://wa.me/?text=${encodeURIComponent(item.script)}`,'_blank')}><MessageCircle size={14}/>Kirim</Button></div></div></article>)}</section>
    {!scripts.isLoading&&!filtered.length&&<div className="rounded-2xl border border-dashed p-10 text-center"><Sparkles className="mx-auto text-zinc-400"/><h3 className="mt-3 font-display font-bold">Skrip tidak ditemukan</h3><p className="mt-1 text-sm text-zinc-400">Coba kata kunci atau tahap percakapan lain.</p></div>}
  </div>;
}
